USE [JobPortal]
GO
SET IDENTITY_INSERT [dbo].[ApplicantDocument] ON 

INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6937, 81, N'hidzer@linuxmail.org', N'Bosun', N'Identification Card (Malaysian/PR)', N'31', N'2', N'821006-04-5129', N'', N'', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023454_Identification Card MalaysianPR.docx', N'.docx')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6942, 81, N'hidzer@linuxmail.org', N'Bosun', N'BOSIET/T-BOSEIT/FOET-T-FOET', N'31', N'9', N'290857071801190333', N'18-Jan-2019', N'17-Jan-2023', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_BOSIETT-BOSEITFOET-T-FOET.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6944, 81, N'hidzer@linuxmail.org', N'Bosun', N'Seaman Book (all pages)', N'31', N'13', N'O00075', N'12-May-2000', N'', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_Seaman Book all pages.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6936, 81, N'hidzer@linuxmail.org', N'Bosun', N'International Passport', N'31', N'1', N'A36146627', N'05-Sep-2015', N'05-Sep-2020', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023454_International Passport.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6938, 81, N'hidzer@linuxmail.org', N'Bosun', N'Able Seafarer Deck/Engine', N'31', N'5', N'A002001', N'', N'', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023454_Able Seafarer DeckEngine.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6939, 81, N'hidzer@linuxmail.org', N'Bosun', N'Malaysia Seaman Card', N'31', N'6', N'200921000120', N'28-Sep-2014', N'27-Sep-2019', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023454_Malaysia Seaman Card.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6941, 81, N'hidzer@linuxmail.org', N'Bosun', N'PETRONAS/PMU Medical', N'31', N'8', N'199951', N'06-Dec-2017', N'05-Dec-2019', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_PETRONASPMU Medical.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6946, 81, N'hidzer@linuxmail.org', N'Bosun', N'Other 1', N'31', N'40', N'', N'', N'', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_Other 1.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6948, 81, N'hidzer@linuxmail.org', N'Bosun', N'Other 3', N'31', N'42', N'', N'', N'', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_Other 3.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6943, 81, N'hidzer@linuxmail.org', N'Bosun', N'H2S', N'31', N'10', N'H2S-A477014/13', N'21-Nov-2013', N'20-Nov-2016', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_H2S.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6947, 81, N'hidzer@linuxmail.org', N'Bosun', N'Other 2', N'31', N'41', N'', N'', N'', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_Other 2.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6940, 81, N'hidzer@linuxmail.org', N'Bosun', N'Marine Department Medical', N'31', N'7', N'168981', N'06-Dec-2017', N'05-Dec-2019', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023454_Marine Department Medical.pdf', N'.pdf')
INSERT [dbo].[ApplicantDocument] ([Id], [ApplyID], [UserID], [Position], [Document], [PositionID], [DocumentID], [DocNo], [DtIssue], [DtExpiry], [Type], [ContentType], [FilePath], [FileName], [FileExtension]) VALUES (6945, 81, N'hidzer@linuxmail.org', N'Bosun', N'Basic Training Certificates', N'31', N'14', N'2094350', N'08-Nov-2016', N'07-Nov-2021', N'', NULL, N'D:\eCrew\UserDoc\', N'31_hidzer@linuxmail.org_20190321023455_Basic Training Certificates.pdf', N'.pdf')

  SET IDENTITY_INSERT [dbo].[ApplicantDocument] OFF 

  DELETE FROM  [dbo].[ApplicantDocument] WHERE UserID = N'hidzer@linuxmail.org'